blog/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostLike, BookingView, SuccessView, UserProfileView, ChangeBookingView, EditBookingView, DeleteBookingView, SuccessDeleteView

urlpatterns = [
    path('', PostList.as_view(), name='index'),
    path('post/<slug:slug>/', PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>/', PostLike.as_view(), name='post_like'),
    path('booking/', BookingView.as_view(), name='booking'),
    path('success_page/', SuccessView.as_view(), name='success_page'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('edit_booking/', EditBookingView.as_view(), name='edit_booking'),
    path('delete_booking/', DeleteBookingView.as_view(), name='delete_booking'),
    path('success_delete_page/', SuccessDeleteView.as_view(), name='success_delete_page'),
]

marisol/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import PostList, PostDetail, PostLike, BookingView, SuccessView, UserProfileView, EditBookingView, DeleteBookingView, SuccessDeleteView
from allauth.account.views import LogoutView
from blog.views import ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostList.as_view(), name='home'),
    path('blog/<slug:slug>/', PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>/', PostLike.as_view(), name='post_like'),
    path('booking/', BookingView.as_view(), name='booking'),
    path('success_page/', SuccessView.as_view(), name='success_page'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/logout/', LogoutView.as_view(), name='account_logout'),
    path('edit_booking/', EditBookingView.as_view(), name='edit_booking'),
    path('delete_booking/', DeleteBookingView.as_view(), name='delete_booking'),
    path('success_delete_page/', SuccessDeleteView.as_view(), name='success_delete_page'),
    path('contacts/', ContactView.as_view(), name='contacts'),
]

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Comment
from .models import CallBooking
import datetime
from datetime import date


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

def get_time_intervals():
    return [
        ('09:00', '9:00 - 10:00'),
        ('10:00', '10:00 - 11:00'),
        ('11:00', '11:00 - 12:00'),
        ('12:00', '12:00 - 13:00'), 
        ('13:00', '13:00 - 14:00'),
        ('14:00', '14:00 - 15:00'),
        ('15:00', '15:00 - 16:00'),
        ('16:00', '16:00 - 17:00'),
        ('17:00', '17:00 - 18:00'),
        ('18:00', '18:00 - 19:00'),
        ('19:00', '19:00 - 20:00'),
    ]

# Form for creating or updating CallBooking instances.
class CallBookingForm(forms.ModelForm):
    client_name = forms.CharField(label='Ім\'я клієнта')
    client_email = forms.EmailField(label='Електронна пошта клієнта')
    phone_number = forms.CharField(label='Номер телефону')
    details = forms.CharField(label='Деталі', widget=forms.Textarea)
    call_date = forms.DateField(label='Дата', widget=DateInput())
    call_time = forms.ChoiceField(choices=get_time_intervals(), label='Оберіть час')

    class Meta:
        model = CallBooking
        fields = ['client_name', 'client_email', 'phone_number', 'details', 'call_date', 'call_time']
        widgets = {
            'call_time': TimeInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['call_date'] = date.today()
        self.fields['call_date'].required = True

    def clean_call_date(self):
        call_date = self.cleaned_data['call_date']
        if call_date <= date.today():
            raise ValidationError('Дата дзвінка не може бути ні минулою, ні сьогоднішньою')
        return call_date


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="uk" class="h-100">

<head>
    <title>Marisol - меблі на замовлення з індивідуальним дизайном</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- Metategs -->
    <meta http-equiv="Content-Language" content="uk">
    <meta name="language" content="Ukrainian">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.7.1/css/lightgallery-bundle.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src=" {% static 'images/marisol-logo.svg' %}" alt="Marisol Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Головна</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}#about-us-title">Про нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}#blog-title">Блог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}#lead">Галерея</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'contacts' %}">Контакти</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Профіль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Вийти</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Зареєструватись</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Увійти</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>    

    <!-- Articles -->
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto">
        <p class="text-center text-white">Слідкуйте за нами:</p>
        <p class="text-center text-white">
            <a href="https://www.facebook.com/profile.php?id=100063961517306" target="_blank" rel="noopener"
                aria-label="Visit our Facebook page (opens in a new tab)"><i
                    class="fab fa-facebook-square ms-3"></i></a>
            <a href="https://www.instagram.com/marisol_mebli/" target="_blank" rel="noopener"
                aria-label="Visit our Instagram page (opens in a new tab)"><i
                    class="fab fa-instagram-square ms-3"></i></a>
        </p>
        <p class="text-center text-white">пров.Степана Бандери, 2/1а, м.Хмельницький</p>
        <p class="text-center text-white">sound.malyuk@gmail.com</p>
        <p class="text-center text-white">+380978116249</p>
    </footer>

    <!-- Bootstrap JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.7.1/lightgallery.min.js"></script>
    <script src="{% static 'js/gallery.js' %}"></script>
</body>

</html>

templates/booking.html
{% extends "base.html" %}
{% load bootstrap4 %}  
{% block content %}

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {% if user.is_authenticated %}
        <p>Select a suitable date and time, and we'll contact you shortly.</p>
        <form method="post">
            {% csrf_token %}
            {{ booking_form.as_p }}
            <label for="id_call_time">Select a time:</label>
            <select id="id_call_time" name="call_time">
                {% for time_slot in available_time_slots %}
                    <option value="{{ time_slot.0 }}" {% if not time_slot.1 %}disabled{% endif %}>{{ time_slot.0 }} - {{ time_slot.1 }}</option>
                {% endfor %}
            </select>
            <button type="submit">Continue booking</button>
        </form>
        {% else %}
        <p>Please, sign up for booking call</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/contacts.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<!-- Тут вміст -->

<!-- Розділ Контакти -->
<section id="contact" class="contact-section">
    <div class="container">
        <h2 class="section-title">Контакти</h2>
        <div class="row">
            <!-- Інформація про контакти -->
            <div class="col-lg-6">
                <h3>Наші контактні дані</h3>
                <p class="contact-info">
                    <strong>Адреса:</strong> провулок Степана Бандери, 2/1а, Хмельницький, Україна<br>
                    <strong>Телефон:</strong> +380 97 811 6249<br>
                    <strong>Електронна пошта:</strong> sound.malyuk@gmail.com
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<!-- Call Booking Block -->
<section class="layout">
  <div class="wrapper">
    <div class="container_description">
      <div class="banner">
        <h1 class="cover-text">
          Меблі на замовлення з індивідуальним дизайном
        </h1>
        <p class="cover-text">
          Замовте консультацію по телефону у нашого спеціаліста у зручний для вас час, і ми вам зателефонуємо вам, щоб відповісти на всі питання щодо матеріалів, дизайну, цін тощо
        </p>
        <button class="book-call-button" onclick="redirectToBooking()">Забронювати консультацію</button>
        <script>
          function redirectToBooking() {
            window.location.href = "{% url 'booking' %}";
          }
        </script>
      </div>
    </div>
  </div>
</section>
<!-- End Call Booking Block -->

<!-- About us Block -->
<div class="container-fluid">
  <div class="row">
    <div class="about">
      <div class="cont">
        <div id="about-us-title">
          <h1>Про нас:</h1>
          <p>Ласкаво просимо до компанії MARISOL! Ми працюємо у меблевій індустрії більше 5 років і базуємося в
            прекрасному українському місті Хмельницький. Ми спеціалізуємося на створенні на замовлення кухонних шаф,
            шаф-купе, меблів для вітальні та дитячих меблів. Наша експертиза полягає у виготовленні всіх типів
            індивідуальних меблів, які відповідають унікальним потребам та перевагам кожного з наших клієнтів.</p>

          <h1>Чому обирають нас:</h1>
          <ul>
            <li>Швидке виготовлення: Ми пишаємося нашим ефективним процесом виробництва, завдяки якому ваші меблі будуть
              готові в найкоротші терміни.</li>
            <li>Великий досвід: Завдяки багаторічному досвіду ми вдосконалили наші навички, щоб забезпечити меблі
              найвищої якості.</li>
            <li>Гарантія: Ми підтримуємо якість нашої роботи та пропонуємо міцну гарантію на всі наші продукти.</li>
            <li>Конкурентні ціни: Ми віримо в те, що пропонуємо найкращу цінність за ваші інвестиції, тому наші ціни
              приємно здивують вас.</li>
            <li>Сучасні матеріали: Ми стежимо за останніми трендами та використовуємо сучасні матеріали для виняткових
              результатів.</li>
          </ul>

          <h2>Індивідуальні рішення для кухонь:</h2>
          <p>Для тих, хто шукає меблі для кухні на замовлення, ми готові допомогти. Наші дизайни варіюються від
            класичних до сучасних стилів, і ми пропонуємо швидке виробництво, сучасний дизайн та матеріали високої
            якості. За допомогою нашого 3D-моделювання ви можете візуалізувати свою мрію про кухню, перш ніж вона стане
            реальністю.</p>
          <p>Незалежно від того, чи йдеться про шафи на замовлення, шафи-купе, меблі для вітальні чи кухні, ми
            гарантуємо вам індивідуальний підхід, вишукане майстерність і меблі, які піднімуть ваші житлові простори на
            новий рівень. Відчуйте зручність та елегантність персоналізованих меблів, які відповідають вашому смаку та
            способу життя. Звертайтеся до нас сьогодні за вашими меблевими потребами!</p>

        </div>
      </div>
    </div>
  <!-- End Call Booking Block -->

    <!-- Blog Entries Column -->
    <div class="col-12 mt-3 left">
      <h2 id="blog-title">БЛОГ</h2>
      <div class="row">
        {% for post in post_list %}
        <div class="col-md-3">
          <div class="card mb-4">
            <div class="card-body">
              <div class="image-container">
                {% if "placeholder" in post.featured_image.url %}
                <img class="card-img-top" src="/static/images/bedroom.jpeg">
                {% else %}
                <img class="card-img-top" src=" {{ post.featured_image.url }}">
                {% endif %}
                <div class="image-flash">
                  <p class="author">Автор: {{ post.author }}</p>
                </div>
              </div>
              <a href="{% url 'post_detail' post.slug %}" class="post-link">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text">{{ post.excerpt }}</p>
              </a>
              <hr />
              <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
                {{ post.number_of_likes }}</p>
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:5 %}
      </div>
      <div class="row">
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
  {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; ПОПЕРЕДНІ </a></li>
      {% endif %}
      {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> ДАЛІ &raquo;</a></li>

      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
<!-- Gallery -->
<div class="cont">
  <div class="page-head">
    <h1>ГАЛЕРЕЯ</h1>
    <p id="lead">Наші попередні роботи</p>
  </div>

  <div class="demo-gallery">
    <ul id="lightgallery">
      <li
        data-responsive="{% static 'images/1-375.webp' %} 375, {% static 'images/1-480.webp' %} 480, {% static 'images/1-800.webp' %} 800"
        data-src="{% static 'images/1-1600.webp' %}"
        data-sub-html="<h4>Кухня без ручок</h4><p>Сучасний дизайн кухні без ручок з гладкими, безшовними поверхнями.</p>">
        <a href="">
          <img class="img-responsive" src="{% static 'images/thumb-1.webp' %}">
          <div class="demo-gallery-poster">
            <img src="https://sachinchoolur.github.io/lightgallery.js/static/img/zoom.png">
          </div>
        </a>
      </li>
      <li
        data-responsive="{% static 'images/2-375.webp' %} 375, {% static 'images/2-480.webp' %} 480, {% static 'images/2-800.webp' %} 800"
        data-src="{% static 'images/2-1600.webp' %}"
        data-sub-html="<h4>Кухня без ручок</h4><p>Сучасний дизайн кухні без ручок з гладкими, безшовними поверхнями.</p>">
        <a href="">
          <img class="img-responsive" src="{% static 'images/thumb-2.webp' %}">
          <div class="demo-gallery-poster">
            <img src="https://sachinchoolur.github.io/lightgallery.js/static/img/zoom.png">
          </div>
        </a>
      </li>
      <li
        data-responsive="{% static 'images/3-375.webp' %} 375, {% static 'images/3-480.webp' %} 480, {% static 'images/3-800.webp' %} 800"
        data-src="{% static 'images/3-1600.webp' %}"
        data-sub-html="<h4>Кухня без ручок</h4><p>Сучасний дизайн кухні без ручок з гладкими, безшовними поверхнями.</p>">
        <a href="">
          <img class="img-responsive" src="{% static 'images/thumb-3.webp' %}">
          <div class="demo-gallery-poster">
            <img src="https://sachinchoolur.github.io/lightgallery.js/static/img/zoom.png">
          </div>
        </a>
      </li>
      <li
        data-responsive="{% static 'images/6-375.webp' %} 375, {% static 'images/6-480.webp' %} 480, {% static 'images/6-800.webp' %} 800"
        data-src="{% static 'images/6-1600.webp' %}"
        data-sub-html="<h4>Кухня без ручок</h4><p>Сучасний дизайн кухні без ручок з гладкими, безшовними поверхнями.</p>">
        <a href="">
          <img class="img-responsive" src="{% static 'images/thumb-6.webp' %}">
          <div class="demo-gallery-poster">
            <img src="https://sachinchoolur.github.io/lightgallery.js/static/img/zoom.png">
          </div>
        </a>
      </li>
    </ul>
    <span class="small">Клацніть на будь-яке зображення, щоб розкрити його на повний екран</span>
  </div>
</div>

<!-- Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
  integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>


{%endblock%}

templates/post_detail.html
{% extends 'base.html' %} 

{% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Коментарі:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> написав:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Ваш коментар очікує на підтвердження адміністратора
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Відправити коментар:</h3>
                <p>Автор: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Відправити</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container">
            <div class="card-profile user-card-full">
                <div class="row m-l-0 m-r-0">
                    <div class="col-sm-4 bg-c-lite-green user-profile">
                        <div class="card-block text-center text-white">
                            <div class="m-b-25">
                                <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius"
                                    alt="Зображення профілю користувача">
                            </div>
                            <h6 class="f-w-600">{{ user.username }}</h6>
                            <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="card-block">
                            <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Інформація</h6>
                            <div class="row">
                                <div class="col-sm-6">
                                    <p class="m-b-10 f-w-600">Ім'я</p>
                                    <h6 class="text-muted f-w-400">{{ user.username }}</h6>
                                </div>
                                <div class="col-sm-6">
                                    <p class="m-b-10 f-w-600">Електронна пошта</p>
                                    <h6 class="text-muted f-w-400">{{ user.email }}</h6>
                                </div>
                            </div>
                        </div>
                        <div class="card-block">
                            {% if last_booking %}
                            <h6 class="m-b-10 f-w-600">Останній заброньований дзвінок</h6>
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Ім'я клієнта</p>
                                <h6 class="text-muted f-w-400">{{ last_booking.client_name }}</h6>
                                <p class="m-b-10 f-w-600">Телефон клієнта</p>
                                <h6 class="text-muted f-w-400">{{ last_booking.phone_number }}</h6>
                                <p class="m-b-10 f-w-600">Електронна пошта клієнта</p>
                                <h6 class="text-muted f-w-400">{{ last_booking.client_email }}</h6>
                                <p class="m-b-10 f-w-600">Дата дзвінка</p>
                                <h6 class="text-muted f-w-400">{{ last_booking.call_date }}</h6>
                                <p class="m-b-10 f-w-600">Час дзвінка</p>
                                <h6 class="text-muted f-w-400">{{ last_booking.call_time }}</h6>
                                <p class="m-b-10 f-w-600">Деталі</p>
                                <h6 class="text-muted f-w-400">{{ last_booking.details }}</h6>
                            </div>
                            {% else %}
                            <h6 class="text-muted f-w-400">У вас немає заброньованих дзвінків</h6>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="control-button">
    {% if last_booking %}
<div id="first_button_profile"><a class="change_booking_button_profile" href="{% url 'edit_booking' %}">Редагувати</a></div>
<div id="second_button_profile"><a class="delete_booking_button_profile" href="{% url 'delete_booking' %}">Видалити бронювання</a></div>
{% endif %}
</div>

{% endblock %}

templates/success_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h1>Call Booking Successful!</h1>
            <p>Thank you for booking a call with us. We have received your request and will contact you at the scheduled
                time.</p>
            <p>If you have any questions or need to reschedule, please contact our support team at support@example.com.
            </p>
            <a class="change_booking_button" href="{% url 'edit_booking' %}">Edit Booking</a>
        </div>
    </div>
</div>
{% endblock %}